### ISSUE TITLE
Cole? Coal!

### ISSUE THREAD

**Issue by Gjum** [NiclasOlofsson/MiNET#11]
https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Blocks/BlockFactory.cs#L29, 107, 109, and possibly some more.

**Comment by FDKPIBC** [comment]
uhhh....NiclasOlofsson will fix that,Thanks for your Suggestion.

**Comment by NiclasOlofsson** [comment]
Thanks. Fixed.
