### ISSUE TITLE
Did the implementation of the FLAT?(how make World Folder?)

### ISSUE THREAD

**Issue by zicwoboo** [NiclasOlofsson/MiNET#122]

**Comment by zicwoboo** [comment]
Please understand that I do not speak English well because i'm kroean and i'm a beginner

**Comment by zicwoboo** [comment]
i can't find a world folder

**Comment by FDKPIBC** [comment]
MiNET do not create any world,so you need do it by yourself,copy your minecraft game saved.

**Comment by kennyvv** [comment]
World saving is not implemented.
