### ISSUE TITLE
Others said me that MiNet does not support Linux..

### ISSUE THREAD

**Issue by darkspive** [NiclasOlofsson/MiNET#128]
Is it true?
It said me : @undrfined
Sorry for my english...

**Comment by undrfined** [comment]
It's supported, i don't said that...

**Comment by darkspive** [comment]
Ты блять говорил мне

**Comment by darkspive** [comment]
Тебе переслать в вк?

**Comment by darkspive** [comment]
U said me

**Comment by darkspive** [comment]
I can resend u your messages

**Comment by MrSN-AG** [comment]
МиНет работает под линуксом. Там как-то надо правильно написать в терминал)

**Comment by darkspive** [comment]
Просто вот че случилось с покетмайном у меня теперь на них бомбит
Translating: it is pocketmine
![screenshot_2016-02-15-22-47-50](https://cloud.githubusercontent.com/assets/14966273/13056628/5115a988-d438-11e5-8fb2-e867af5a6889.png)

**Comment by MrSN-AG** [comment]
Бекап, не?

15.02.2016, 21:04, "darkspive" <notifications@github.com>:
> Просто вот че случилось с покетмайном у меня теперь на них бомбит
> Translating: it is pocketmine
>
> —
> Reply to this email directly or view it on GitHub.

Su pagarba, 
Aleksandras Gaiduchik 
------------------------------------------- 
Vkontakte: http://vk.com/al.rudskoy 
Skype: rover-alex.com

**Comment by darkspive** [comment]
Там у них какая то херня с batch пакетами

**Comment by darkspive** [comment]
To dev: can u add simply installing?

**Comment by NiclasOlofsson** [comment]
Seems i seriously have to turn off issues. There are simply too many idiots out there.
