### ISSUE TITLE
Water Won't Remove Plants

### ISSUE THREAD

**Issue by josevazqm** [NiclasOlofsson/MiNET#16]
As the title says, water won't remove plants when placed.

**Comment by NiclasOlofsson** [comment]
You are absolutely right. Metadata on many of the Blocks are as of this time not yet implemented, and this specific funtionality depend on that. Since implementing the metadata is a shitload of work, I'm hoping someone will step up and help out on that.

**Comment by vvzar** [comment]
is any algorythms for metadata already done?
I can make routing operations like adding repeated strings or something like this.
