### ISSUE TITLE
error in Plugins/PluginManager.cs

### ISSUE THREAD

**Issue by vvzar** [NiclasOlofsson/MiNET#19]
Errors:
 
/home/minecraft/MiNET/src/MiNET/MiNET.sln (default targets)
->
(Build target) ->
/home/minecraft/MiNET/src/MiNET/MiNET/MiNET.csproj (default
targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile targ
et) ->
 
        Plugins/PluginManager.cs(212,38): error CS1684: Refe
rence to type `System.Security.Claims.ClaimsIdentity' claims
 it is defined assembly `mscorlib, Version=4.0.0.0, Culture=
neutral, PublicKeyToken=b77a5c561934e089', but it could not
be found
 
         6 Warning(s)
         1 Error(s)
 
Time Elapsed 00:00:03.6056490

project cant made. Why?
Ubuntu x64 14.04 all steps passed succesfully

**Comment by FDKPIBC** [comment]
The mono is latest version?

**Comment by NiclasOlofsson** [comment]
This seems to be because mono didn't implement it. In fact, it seems most of security is in in-implemented. I will need to look into how security can be supported on mono.

**Comment by vvzar** [comment]
Thank You for your time! I connected repo from mono-project and installed 3.12 version. And the other packages like mono-devel , referenceassemblies-pcl  and again mono-complete.
All done! and i have running server :)

Is any configuration parameters that i can learn ?
