### ISSUE TITLE
I Update a ListCommand.cs(maybe your need it or not)

### ISSUE THREAD

**Issue by FDKPIBC** [NiclasOlofsson/MiNET#2]
Code:

namespace MiNET.CommandHandler
{
    internal class ListCommand : ICommandHandler
    {
        public string Command
        {
            get { return "list"; }
        }

        public string Description
        {
            get { return "View all OnLine players from this server."; }
        }

        public string Usage
        {
            get { return "/list"; }
        }

        public string Permission
        {
            get { return "MiNET.list"; }
        }

        public static string GetList(Player player)
        {
            string OnLinePlayerlist = null;
            MiNET.Worlds.Level level = player.Level;
            for(int i =0;i<level.Players.Count;i++)
            {
                int Count = i + 1;
                OnLinePlayerlist = "["+ Count +"]" + level.Players[i].ToString();
                OnLinePlayerlist += "\r\n";
            }
            return OnLinePlayerlist;
        }

        public bool Execute(Player player, string[] arguments)
        {
            if (arguments.Length >= 1)
            {
                GetList(player);
                return true;
            }
            return false;
        }
    }
}
//maybe it unusefull

**Comment by kennyvv** [comment]
First of all, thanks for your support!
However i took a look at your code. It doesn't really make sence.
I'll explain why.

1. You check if there is atleast 1 argument, however you never actually use it anywhere.
2. You get a list of players and you return it, afterwards you never use it.
3. In your GetList method, you do level.Players[i].ToString(), you probably meant to do level.Players[i].Username.

Please next time use a pull request, and check your code before you send it to us :)
We appreciate the help tho!

Greetings, Kenny

**Comment by FDKPIBC** [comment]
Unable using pull requests？@kennyvv
