### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by Bond-009** [NiclasOlofsson/MiNET#234]
It would be awesome if this project uses .Net Core instead of the .Net Framework. That way it would support macOS and Linux.

**Comment by Polo1K** [comment]
It only takes 20 minutes of a semi-experienced developer to add Mono support, it would be an insane amount of work to port to .NET Core which is missing features from the .NET Framework used in MiNET.

**Comment by Bond-009** [comment]
Except for System.Drawing, what is missing?

**Comment by Polo1K** [comment]
Perhaps.... practically all of the native encryption stuff? @Bond-009

**Comment by FDKPIBC** [comment]
@Bond-009 well,Some nuget class libraries do not support .netcore

**Comment by NiclasOlofsson** [comment]
I've already tried porting it to .NET core. The sad fact about it is that you still be running mono, so it doesn't matter much.

**Comment by Bond-009** [comment]
`The sad fact about it is that you still be running mono` What do you mean?

**Comment by mhsjlw** [comment]
Looks to me like https://developer.xamarin.com/api/type/System.Security.Cryptography.Aes/ is cross-platform

**Comment by NiclasOlofsson** [comment]
@mhsjlw this question was about .NET core, and now we back on mono again.

**Comment by mhsjlw** [comment]
This is in response to @Polo1K's comment. I believe that .NET Core is *not* the issue, but rather running it on Mono *is*. He even states 

> That way it would support macOS and Linux.

I believe that this topic should be changed to a port to support the Mono framework. Please confirm @Bond-009

**Comment by Bond-009** [comment]
@mhsjlw No, I mean a port to .Net Core, which is officially supported by Microsoft. Mono isn't.

**Comment by kennyvv** [comment]
Lets be honest here, .net core is not in the state we need it to be yet.
I'd say, look back into it when .NET Core 2.0 releases.

**Comment by Bond-009** [comment]
I haven't had any problems since 1.1.

**Comment by NiclasOlofsson** [comment]
.NET Core is not a "problem" @Bond-009. We are not talking about bugs, we are talking about lack of features. I happen to agree 110% with @kennyvv on the wait til earliest a stable 2.0 is out with all what it means.

To all people suggesting xamarin and other stuff, that's just mono based implementations. Xamarin may however have something to offer to the Mac people that regular mono doesn't. So I'd try with that if you want Mac support with encryption.

When I shift MiNET to .NET Core, it needs to be ready with all libs to receive it too. It's not just MiNET. The other libs need to be able to handle the transfer too.

**Comment by mhsjlw** [comment]
Mac support would be interesting, but still not ideal for production. As of right now I'm just running an instance on a Windows Nano Server and it works just fine

**Comment by NiclasOlofsson** [comment]
@mhsjlw Get on gitter and describe that nano-server to me. Sounds interesting.

**Comment by mhsjlw** [comment]
https://icanhasdot.net/result?github=NiclasOlofsson~2FMiNET 

.NET Core 2 is now released

**Comment by DefinitlyEvil** [comment]
awesome

**Comment by NiclasOlofsson** [comment]
About time i close this as completed now :-)
