### ISSUE TITLE
Good installation tutorial

### ISSUE THREAD

**Issue by XDqrkneZ** [NiclasOlofsson/MiNET#236]
Hello, I've watched Bamuel's MiNET tutorial so many times but I still don't get how to make MiNET run on a VPS. If anyone's kind enough to make one or send me instructions.. that would be appreciated and I will make an updated installation video for this.. hope that this is not much to ask

**Comment by FDKPIBC** [comment]
if you have a vps support windows server 2012+,and [get the complete zip](https://ci.appveyor.com/project/NiclasOlofsson/minet/build/artifacts),unzip it,edit server.conf,and start your server...

**Comment by NiclasOlofsson** [comment]
Sorry, but a VPS is no differnet from a regular server.

**Comment by XDqrkneZ** [comment]
oh i see
