### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Ian1971** [NiclasOlofsson/MiNET#237]
I am trying to connect using MC Windows 10 edition. I get the error logged
"ERROR [rlds.Level] - Time between World tick too too long: 100 ms"
In conf I have WorldProvider set to flat and I got the world by unzipping a MCPE world.
Is this the correct provider?

I tried anvil and that gave me "Could not auto-detect compression format"

I also tried a MC classic java world with anvil and that seemed to load but had the "ERROR [rlds.Level] - Time between World tick too too long: 100 ms" problem (it also complained about some block ids but that is probably expected I assume as java world blocks not all available in PE?)

It feels like a network issue. I am just connecting to local server (on local host). It appears in the list in Minecraft Windows 10 as a LAN server but does not connect.

Any ideas?

**Comment by FDKPIBC** [comment]
if you start server in the localhost,you dont use port 19132,when you connect the server in the seem pc plz write your ip address,its not like 192.168.xxx.xxx or 127.0.0.1...

**Comment by Ian1971** [comment]
You mean in MC Windows 10 connection details use my external ip address and the configured port?

**Comment by Ian1971** [comment]
Figured it out. I had only port forwarded TCP. Once I add UDP it started working
