### ISSUE TITLE
The MiNET service is now running, press Control+C to exit

### ISSUE THREAD

**Issue by XDqrkneZ** [NiclasOlofsson/MiNET#241]
I ran minet.service and I get this The MiNET service is now running, press Control+C to exit

**Comment by NiclasOlofsson** [comment]
Very fine!

**Comment by XDqrkneZ** [comment]
how am I supposed to go to the console? How do i get the server IP? I am very sorry for the bother @NiclasOlofsson

**Comment by NiclasOlofsson** [comment]
All I can suggest is http://forums.pocketmine.net/

**Comment by XDqrkneZ** [comment]
@NiclasOlofsson but MiNET is Good software and i really want to try it out

**Comment by FDKPIBC** [comment]
so you should know how to use google to find answer for you want.
and if you wanna make a console to running MiNET you just create it by yourself,for now on,the minet is running as a system service.
