### ISSUE TITLE
Arrow hit detection not precise

### ISSUE THREAD

**Issue by wiez** [NiclasOlofsson/MiNET#26]
When shooting an arrow far away or at a sharp angle, the arrow will usually land a block further than MiNet detects.

![wrong arrow hit detection](https://cloud.githubusercontent.com/assets/4592319/8261635/44a2f75c-16cc-11e5-8e84-a8213f4e91ad.png)

**Comment by kennyvv** [comment]
Thank you for telling us. We'll look at it.
What i understand tho, the "algorithm" for entity's like arrows isn't completely done.
