### ISSUE TITLE
Ladders don't work, gamemode bug.

### ISSUE THREAD

**Issue by Creepername** [NiclasOlofsson/MiNET#265]
I placed a ladder, server didn't think so. When I rejoin server the ladder disappears.

I change gamemode from survival to creative - when I break a block, i see drop.
I change gamemode from adventure to creative - I can't break any block.
Sorry for bad english.

**Comment by FDKPIBC** [comment]
https://github.com/NiclasOlofsson/MiNET/issues/261

**Comment by NiclasOlofsson** [comment]
Tested, works.
