### ISSUE TITLE
I have no idea how to describe this

### ISSUE THREAD

**Issue by jrodr10** [NiclasOlofsson/MiNET#266]
Errors:

/home/MiNET/src/MiNET/MiNET.sln (default targets) ->
(Build target) ->
/home/MiNET/src/MiNET/MiNET/MiNET.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        LoginMessageHandler.cs(314,8): error CS0246: The type or namespace name `ECDiffieHellmanCng' could not be found. Are you missing an assembly reference?
        LoginMessageHandler.cs(315,8): error CS0841: A local variable `ecKey' cannot be used before it is declared
        LoginMessageHandler.cs(316,38): error CS0103: The name `ECDiffieHellmanKeyDerivationFunction' does not exist in the current context
        LoginMessageHandler.cs(316,8): error CS0841: A local variable `ecKey' cannot be used before it is declared
        LoginMessageHandler.cs(317,8): error CS0841: A local variable `ecKey' cannot be used before it is declared
        LoginMessageHandler.cs(319,24): error CS0841: A local variable `ecKey' cannot be used before it is declared
        LoginMessageHandler.cs(355,58): error CS0841: A local variable `ecKey' cannot be used before it is declared
        LoginMessageHandler.cs(356,39): error CS0841: A local variable `ecKey' cannot be used before it is declared
        LoginMessageHandler.cs(357,25): error CS0841: A local variable `ecKey' cannot be used before it is declared
        Utils/CryptoUtils.cs(61,41): error CS0103: The name `ECDiffieHellmanCngPublicKey' does not exist in the current context
        Utils/CryptoUtils.cs(82,11): error CS0103: The name `ECDiffieHellmanCngPublicKey' does not exist in the current context
        Utils/CryptoUtils.cs(191,4): error CS0246: The type or namespace name `ECDiffieHellmanCng' could not be found. Are you missing an assembly reference?
        Utils/CryptoUtils.cs(192,4): error CS0841: A local variable `ecKey' cannot be used before it is declared
        Utils/CryptoUtils.cs(193,34): error CS0103: The name `ECDiffieHellmanKeyDerivationFunction' does not exist in the current context
        Utils/CryptoUtils.cs(193,4): error CS0841: A local variable `ecKey' cannot be used before it is declared
        Utils/CryptoUtils.cs(195,43): error CS0841: A local variable `ecKey' cannot be used before it is declared
        Utils/CryptoUtils.cs(242,4): error CS0246: The type or namespace name `ECDiffieHellmanCng' could not be found. Are you missing an assembly reference?
        Utils/CryptoUtils.cs(243,4): error CS0841: A local variable `ecKey' cannot be used before it is declared
        Utils/CryptoUtils.cs(244,34): error CS0103: The name `ECDiffieHellmanKeyDerivationFunction' does not exist in the current context
        Utils/CryptoUtils.cs(244,4): error CS0841: A local variable `ecKey' cannot be used before it is declared
        Utils/CryptoUtils.cs(246,34): error CS0841: A local variable `ecKey' cannot be used before it is declared

         21 Warning(s)
         21 Error(s)

Time Elapsed 00:00:01.9783950
root@rdrpe:/home/MiNET#

**Comment by dktapps** [comment]
`MCPE 0.15 introduced a lot of crypto, which is not implemented on Mono. So until another solution comes along, Mono support is not possible.`

**Comment by jrodr10** [comment]
I was under the impression it was supported, i apologize.

**Comment by NiclasOlofsson** [comment]
It works, just not supported.

**Comment by jrodr10** [comment]
rip, i was happy for a moment
