### ISSUE TITLE
Implement Ladders / Vines

### ISSUE THREAD

**Issue by goerick** [NiclasOlofsson/MiNET#29]
when you place a latter, there is a huge lag spike then the latter disappears

**Comment by kennyvv** [comment]
I'm guessing you mean a Ladder. Ladders are not yet implemented.

**Comment by goerick** [comment]
Oh ok this applies to vines as well

**Comment by RandomAltThing** [comment]
Ladders work however vines do not. You cannot even placr vines.

**Comment by Synchunky** [comment]
This fixed yet?
