### ISSUE TITLE
Implement fire correctly.

### ISSUE THREAD

**Issue by goerick** [NiclasOlofsson/MiNET#30]
when you light a Minecart track with flint and steel the flame doesn't appear but it illuminates the track

**Comment by kennyvv** [comment]
This is caused because flames/fire is not currently implemented correctly.
Should be done later.

**Comment by NiclasOlofsson** [comment]
This is il just fine. Compare with vanilla and you will see the same there.

**Comment by kennyvv** [comment]
NiclasOlofsson, it is not really behavior we want tho... It is just like when u place fire, and remove the block below it. Fire still there, however you can't see it.

**Comment by NiclasOlofsson** [comment]
I see. Yes, that is correct that it's wrong :-)

**Comment by RandomAltThing** [comment]
This is also a bug in PocketMine so don't sorry ;)

**Comment by NiclasOlofsson** [comment]
Check the code. Need to have proper data for the blocks for this to work. It's the same problem as when water doesn't remove some of the plants and similar.
