### ISSUE TITLE
List of glitches and implementation 

### ISSUE THREAD

**Issue by goerick** [NiclasOlofsson/MiNET#34]
-[IMPROVE] Chest don't become double chest when placed next to each other.
-[IMPROVE] Gravel/Sand Doesn't fall
-[IMPROVE] Can place non 1 X 1 blocks directly on top and next to each other (snow, plants, mushrooms, flowers, etc)
-[BUG] Arrows don't get absorbed by player when you hit a player with a arrow.
-Player gets a hurt display both client visible and the person who is seeing it in creatie mode
-[FIXED] Player takes damage in creative mode
-[FIXED] No knock back aka flinch when hurting
-[FIXED] Player dies in creative mode by physical damage
-[BUG] No animation of tool use (sword, bow, etc) 
-[IMPROVE] Bonemeal doesn't work
-[IMPROVE] Ice doesn't melt near light source
-[IMPROVE] plants don't die when the grass under them gets destroyed/replaced
-[IMPROVE] No leave decay
-[IMPROVE] You can plae grass only plants anywhere
-[FIXED] Respawn button doesn't work when killed
-[IMPROVE] Can place mushrooms in lighted place
-[BUG] Arrows don't burn in fire 

Edit:
-[IMPROVE] Fire doesn't change lighting
-[IMPROVE] When say turns to night light sources like torches light only the block they are on

Edit 3:
-[BUG] When set on fire and leave fire source, the first person fire display should still appear
-[BUG] When a player is set on fire, they should be seen having fire animation by another player
-[FIXED] You can die in creatie mode with fire
-[BUG] You can be set on fire in creative mode
-[BUG] You can flit and steel on the side of any lock and if non flammable block it will light the surrounding areas

Edit: 4
-[IMPROVE] Melons/Pumpkins do not grow
-[IMPROVE] When placing a melon/pumpkin next to a stem, the stem does not attach to the melon/pumpkin
-[IMPROVE] soil does not become dirt when jumped on
-[IMPROVE] soil does not fertilize when near water 
Edit 5:
-[IMPROVE] Bone meal does not work on coca
-[FIXED] When doubt tappig dirt with shovel it does not become a trail

-[IMPROVE/BUG] Huge and considerable amount of lag when placing/breaking blocks. This is because the entire map recalculated it lighting aka it becomes dark then light again. If you have a really under graded device or high ping you can see this happen. It is probably experienced in old under graded hardware or clients with high ping. My iPhone 4s lags when placing or relaxing blocks but my Samsung Galaxy s5 have minimal but occasional lag spikes when placing or breaking blocks

**Comment by goerick** [comment]
Edit 3:
-When set on fire and leave fire source, the first person fire display should still appear
-When a player is set on fire, they should be seen having fire animation by another player
-You can die in creatie mode with fire
-You can be set on fire in creative mode
-You can flit and steel on the side of any lock and if non flammable block it will light the surrounding areas

**Comment by Creeperface01** [comment]
a lot of features are not implenteed but i think this project is best of all server projects for MCPE :)

**Comment by goerick** [comment]
Nah I'm not expecting instant fixes. This is just a "to do" list and "just in case if you forget".

**Comment by goerick** [comment]
Edit: 4
-Melons/Pumpkins do not grow
-When placing a melon/pumpkin next to a stem, the stem does not attach to the melon/pumpkin
-soil does not become dirt when jumped on
-soil does not fertilize when near water

**Comment by goerick** [comment]
Edit 5:
-Bone meal does not work on coca
-When doubt tappig dirt with shovel it does not become a trail

-Huge and considerable amount of lag when placing/breaking blocks. This is because the entire map recalculated it lighting aka it becomes dark then light again. If you have a really under graded device or high ping you can see this happen. It is probably experienced in old under graded hardware or clients with high ping. My iPhone 4s lags when placing or relaxing blocks but my Samsung Galaxy s5 have minimal but occasional lag spikes when placing or breaking blocks

**Comment by NiclasOlofsson** [comment]
Regardnig the lights; Yeah even on my fairly fast iPad i can see the light recalculation going throw the world as a chock-wave. Almost looks like a nuke-effect :-)

I appreciate the list.

**Comment by NiclasOlofsson** [comment]
@goerick Let me just explain that the features not directly related to "online gaming" (like farming) has a tendency of getting at the end of the backlog. But since I do enjoy doing some of the more tricker logic in MC I'll might go through some from this list sooner rather than later.

**Comment by goerick** [comment]
Yes I wish I could help by fixing some issues on this list but I can only code in Python sadly

**Comment by Creeperface01** [comment]
@NiclasOlofsson can you use files from MCPE?

**Comment by NiclasOlofsson** [comment]
@Creeperface01 Sorry, this is not a forum.

**Comment by Creeperface01** [comment]
Ok so where is the minet fórum?

**Comment by kennyvv** [comment]
@Creeperface01 We currently don't have an official forum.
Please join gitter for questions.

**Comment by RandomAltThing** [comment]
Or twitter**

**Comment by FDKPIBC** [comment]
or  my server will be back

**Comment by NiclasOlofsson** [comment]
One things is for sure, this is not and gitter and IRC are the only ones i use.

**Comment by goerick** [comment]
If its fixed, just put FIXED beside the names. Closing due to spam.

**Comment by NiclasOlofsson** [comment]
This is a good list, i've locked it for comments (no more spam) and will keep it open while working on fixing the issues around farming.
