### ISSUE TITLE
Idea for permissions

### ISSUE THREAD

**Issue by RandomAltThing** [NiclasOlofsson/MiNET#37]
Permissions should be like this:
<pre>
public bool Execute(Player player, string[] arguments)
		{
			if (arguments.Length >= 1 && player.hasPermission("!MiNET.kick.others"){
			{
				player.sendMessage("You do not have permission to use this command");
				return false;
			} else{
         player.sendMessage("/kick <player>");
    return true;
       }
	}
		}
</pre>

**Comment by NiclasOlofsson** [comment]
The security is rolebased and through properties usually. Example: [Authorize(Roles = "ADMIN, OP")]

**Comment by PEMapModder** [comment]
What,  `player.sendMessage("/kick ") ;`5?
