### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by gzachrisson** [NiclasOlofsson/MiNET#396]
The build instructions on the wiki and the README need to be updated now after the switch to .NET Core 2.0. Especially for Linux. The MiNET.Service for example is no longer built (at least not for me) as mentioned in the build instructions for Linux.

**Comment by Mates1500** [comment]
I've updated the [instructions](https://github.com/NiclasOlofsson/MiNET/wiki/Getting-Started) for .NET Core a couple of days ago.
