### ISSUE TITLE
Error when trying to build for linux

### ISSUE THREAD

**Issue by HughSparks** [NiclasOlofsson/MiNET#400]
When I use the ms build to compile the programs it gives a warning and an error and i have not seen any on your issue page that resemble mine.

it gives this error:

![error](https://user-images.githubusercontent.com/28938999/42796234-91b15dea-893d-11e8-8a43-cc6e60193535.PNG)

hope yall can help

**Comment by kennyvv** [comment]
MiNET is targeted for Dotnet Core, this does not use MSBuild. The instructions are outdated.

**Comment by dschwartz783** [comment]
Also worth pointing out that FreeNAS is not Linux, but based on FreeBSD.

**Comment by einerixcode** [comment]
Try to build it in Visual Studio with a .NET Core Project
