### ISSUE TITLE
Packet handling too long 1450 ms 

### ISSUE THREAD

**Issue by Timurinyo** [NiclasOlofsson/MiNET#435]
Minecraft education edition 1.7.1. Trying to connect to 127.0.0.1. After writing Connection established server writes Packet handling too long 1450 ms for 16. Where 16 is my player name. Then TIMEOUT.., Closed network session... Disconnected... reason: Network timeout

What is wrong?

**Comment by oas** [comment]
I can reproduce the issue. Minecraft: Education Edition 1.7.1, latest version of MEENET (1.7.7):
```
WARN [?] - Encryption enabled for Jonas
WARN [?] - Packet (0x01) handling too long 1716ms for Jonas
WARN [?] - Connection established with Jonas using MC version 1.7.1 with protocol version 291
WARN [?] - No commands to send
WARN [?] - Started processing thread for Jonas
WARN [?] - Jonas - Wrong sequence. Expected 15, but was 22.
WARN [?] - Jonas - Wrong sequence. Expected 15, but was 22.
WARN [?] - Jonas - Wrong sequence. Expected 15, but was 16.
WARN [?] - Jonas - Wrong sequence. Expected 15, but was 16.
[...]
```

**Comment by NiclasOlofsson** [comment]
May be something related to Microsoft authentication. I'll have to investigate this.
