### ISSUE TITLE
Update to 1.10

### ISSUE THREAD

**Issue by KKDevelop** [NiclasOlofsson/MiNET#450]
When did you upgrade your kernel to 1.10?

**Comment by dktapps** [comment]
never, as you can see

**Comment by endervlad** [comment]
@dktapps I am going to update it with time.

**Comment by dktapps** [comment]
I'm just shitposting @endervlad don't mind me :P

**Comment by DanielK1511** [comment]
@endervlad, when is it gonna drop?

**Comment by endervlad** [comment]
@DanielK1511 You can download .zip file of minet-server from appveyor, just press "Current build" button.

**Comment by DanielK1511** [comment]
@endervlad whats appveyor?
