### ISSUE TITLE
hello when I follow this documents,I got this mistake

### ISSUE THREAD

**Issue by TKBSTMYN** [NiclasOlofsson/MiNET#469]
root@iZwz9b8z1fqaq4sbklzy8xZ:/home/minet/src/MiNET/MiNET.Console# dotnet build /home/minet/src/MiNET/MiNET.sln
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/home/minet/src/MiNET/MiNET.BuilderBase/MiNET.BuilderBase.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
  Restore completed in 75.75 ms for /home/minet/src/MiNET/MiNET.BuilderBase/MiNET.BuilderBase.csproj.
/home/minet/src/MiNET/MiNET.Client/MiNET.Client.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
  Restore completed in 6.44 ms for /home/minet/src/MiNET/MiNET.Client/MiNET.Client.csproj.
/home/minet/src/MiNET/MiNET.Console/MiNET.Console.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
  Restore completed in 3.27 ms for /home/minet/src/MiNET/MiNET.Console/MiNET.Console.csproj.
/home/minet/src/MiNET/MiNET.Plotter/MiNET.Plotter.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
  Restore completed in 5.16 ms for /home/minet/src/MiNET/MiNET.Plotter/MiNET.Plotter.csproj.
/home/minet/src/MiNET/MiNET.ServiceKiller/MiNET.ServiceKiller.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
  Restore completed in 3.69 ms for /home/minet/src/MiNET/MiNET.ServiceKiller/MiNET.ServiceKiller.csproj.
/home/minet/src/MiNET/MiNET.Test/MiNET.Test.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
  Restore completed in 22.64 ms for /home/minet/src/MiNET/MiNET.Test/MiNET.Test.csproj.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
  Restore completed in 3.24 ms for /home/minet/src/MiNET/MiNET/MiNET.csproj.
/home/minet/src/MiNET/TestPlugin/TestPlugin.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
  Restore completed in 2.1 ms for /home/minet/src/MiNET/TestPlugin/TestPlugin.csproj.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
  MiNET -> /home/minet/src/MiNET/MiNET/bin/Debug/netcoreapp2.1/MiNET.dll
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET.Console/MiNET.Console.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
  MiNET.Console -> /home/minet/src/MiNET/MiNET.Console/bin/Debug/netcoreapp2.1/MiNET.Console.dll
/home/minet/src/MiNET/MiNET.Test/MiNET.Test.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET.Client/MiNET.Client.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
  MiNET.Client -> /home/minet/src/MiNET/MiNET.Client/bin/Debug/netcoreapp2.1/MiNET.Client.dll
  MiNET.Test -> /home/minet/src/MiNET/MiNET.Test/bin/Debug/netcoreapp2.1/MiNET.Test.dll
/home/minet/src/MiNET/MiNET.ServiceKiller/MiNET.ServiceKiller.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
  MiNET.ServiceKiller -> /home/minet/src/MiNET/MiNET.ServiceKiller/bin/Debug/netcoreapp2.1/MiNET.ServiceKiller.dll
/home/minet/src/MiNET/TestPlugin/TestPlugin.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
  TestPlugin -> /home/minet/src/MiNET/TestPlugin/bin/Debug/netcoreapp2.1/TestPlugin.dll
/home/minet/src/MiNET/MiNET.Plotter/MiNET.Plotter.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
  MiNET.Plotter -> /home/minet/src/MiNET/MiNET.Plotter/bin/Debug/netcoreapp2.1/MiNET.Plotter.dll
/home/minet/src/MiNET/MiNET.BuilderBase/MiNET.BuilderBase.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
  MiNET.BuilderBase -> /home/minet/src/MiNET/MiNET.BuilderBase/bin/Debug/netcoreapp2.1/MiNET.BuilderBase.dll

Build succeeded.

/home/minet/src/MiNET/MiNET.BuilderBase/MiNET.BuilderBase.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
/home/minet/src/MiNET/MiNET.Client/MiNET.Client.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
/home/minet/src/MiNET/MiNET.Console/MiNET.Console.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
/home/minet/src/MiNET/MiNET.Plotter/MiNET.Plotter.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
/home/minet/src/MiNET/MiNET.ServiceKiller/MiNET.ServiceKiller.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
/home/minet/src/MiNET/MiNET.Test/MiNET.Test.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
/home/minet/src/MiNET/TestPlugin/TestPlugin.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.sln]
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET.Console/MiNET.Console.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET.Test/MiNET.Test.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET.Client/MiNET.Client.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET.ServiceKiller/MiNET.ServiceKiller.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/TestPlugin/TestPlugin.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET.Plotter/MiNET.Plotter.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET.BuilderBase/MiNET.BuilderBase.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
    18 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.11
root@iZwz9b8z1fqaq4sbklzy8xZ:/home/minet/src/MiNET/MiNET.Console# dotnet run
/home/minet/src/MiNET/MiNET.Console/MiNET.Console.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. [/home/minet/src/MiNET/MiNET.Console/MiNET.Console.csproj]
/home/minet/src/MiNET/MiNET.Console/MiNET.Console.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/minet/src/MiNET/MiNET/MiNET.csproj : warning NU1701: Package 'SharpAvi 2.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

 __   __  ___   __    _  _______  _______
|  |_|  ||   | |  |  | ||       ||       |
|       ||   | |   |_| ||    ___||_     _|
|       ||   | |       ||   |___   |   |
|       ||   | |  _    ||    ___|  |   |
| ||_|| ||   | | | |   ||   |___   |   |
|_|   |_||___| |_|  |__||_______|  |___|

Are you blessed with HW accelerated vectors? Yep!
Operations timed using the system's high-resolution performance counter.
  Timer frequency in ticks per second = 1000000000
  Timer is accurate within 1 nanoseconds
 WARN [?] - No level.dat found at /home/minet/src/MiNET/MiNET/Worlds/level.dat. Creating empty.
 WARN [?] - No level.dat found at /home/minet/src/MiNET/MiNET/Worlds/level.dat. Creating empty.
 WARN [?] - No level.dat found at /home/minet/src/MiNET/MiNET/Worlds/level.dat. Creating empty.
 WARN [?] - Time between world tick too long: 69 ms. Last processing time=0, Avarage=50
MiNET running. Press <enter> to stop service.
 WARN [?] - Unloaded 12 chunks, 1245 chunks remain cached
 WARN [?] - Unloaded 12 chunks, 1245 chunks remain cached
 WARN [?] - Unloaded 12 chunks, 1245 chunks remain cached
sscdss
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
 WARN [?] - Unexpected end of transmission?
root@iZwz9b8z1fqaq4sbklzy8xZ:/home/minet/src/MiNET/MiNET.Console#

**Comment by TKBSTMYN** [comment]
my system is Ubuntu 16.04

**Comment by NiclasOlofsson** [comment]
Are you trying to connect to it, or does it just happen?

**Comment by undrfined** [comment]
@TKBSTMYN could you please send the `minetlog.log` file?

**Comment by NiclasOlofsson** [comment]
TIO slow

**Comment by TKBSTMYN** [comment]
sorry,I am a Chinese high middle school student
I'm too tired on my study and can't online these days
I will contact you as soon as possible.
thank you!
