### ISSUE TITLE
Disconnect crashed player 

### ISSUE THREAD

**Issue by seyong92** [NiclasOlofsson/MiNET#475]
I cannot connect to my MiNET server with Minecraft Android. When I try to connect the server, then the Minecraft client app is crashed, and the server prints out the error.

Here are the error and warning related. I just hide my username and IP.

ERROR [PlayerNetworkSession] - Unhandled packet: McpeClientCacheStatus 0x81 for user: USERNAME, IP xxx.xxx.xxx.xxx
 WARN [PlayerNetworkSession] - Unknown packet 0x81
01                                               .

 WARN [McpeAvailableCommands] - No commands to send
 WARN [PlayerNetworkSession] - Started processing thread for Sanon92
 WARN [PlayerNetworkSession] - USERNAME - Resent. Expected 6, but was 5.
 WARN [PlayerNetworkSession] - TIMEOUT, Resent #71 Type: 10 (0x0a) for USERNAME (1018 > 922) RTO 461
 WARN [PlayerNetworkSession] - TIMEOUT, Resent #72 Type: 10 (0x0a) for USERNAME (2128 > 1844) RTO 461
 WARN [PlayerNetworkSession] - Closed network session for player USERNAME
 WARN [Player] - Disconnected crashed player from level <Overworld>, reason: You've been kicked with reason: Network timeout.

**Comment by NiclasOlofsson** [comment]
MiNET doesn't support 1.13. Are you using a 1.13 client?

**Comment by NiclasOlofsson** [comment]
Yes, he is.
