### ISSUE TITLE
Got <Null> chunk at certain coordinates.

### ISSUE THREAD

**Issue by ReenduX** [NiclasOlofsson/MiNET#482]
When I use anvil as the world provider, I get this:
![obraz](https://user-images.githubusercontent.com/29517406/75097835-70e64b80-55af-11ea-84b1-255514adf2a8.png)
The in-game world looks just like the one using flat world provider.
Using latest master branch.

**Comment by NiclasOlofsson** [comment]
What version was the Anvil files you used for this? MiNET doesn't support anything new on that, after they introduced blockstates in JE.

**Comment by ReenduX** [comment]
I don't used any Anvil files. I expected that MiNET will generate world on it's own.
The "cool" world provider couldn't find block state.
The "experimental" world provider works, but throws this error:
![obraz](https://user-images.githubusercontent.com/29517406/75115904-67b6b680-5663-11ea-903f-303bc7119654.png)

**Comment by NiclasOlofsson** [comment]
Yeah none of the other providers are really supported. They are just there for history. I have to look at it then, because that stuff works just fine for me.

**Comment by ReenduX** [comment]
The "experimental" provider is also "just there for history"? Cuz world looks really good and I could try to fix it.
