### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by V1rusFalcon** [NiclasOlofsson/MiNET#488]
can MiNet generate a normal world or it can only a flat one or the cool one?

**Comment by DarkLexFirst** [comment]
https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET.Console/Startup.cs#L54-L58

**Comment by V1rusFalcon** [comment]
it start another process but doesn't generate a world by it self like nukkit

**Comment by NiclasOlofsson** [comment]
No, MiNET doesn't support world gen.
