### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by DarkFineFirs** [NiclasOlofsson/MiNET#489]
How to install for ubuntu?

**Comment by Heath123** [comment]
This was closed without an answer?

**Comment by spideyroc1** [comment]
No support I believe so getting it running on there is on your own

**Comment by NiclasOlofsson** [comment]
What do you mean "no support". It's .NET Core and that works just fine on Linux, whichever basically. So it's a non-question. I would start by asking "have you tried google" but didn't want to be rude.

**Comment by mclauncherlinux** [comment]
> How to install for ubuntu?

I can recommend QEMU/KVM, I get the best performance when MiNET is running on (windows) server core
