### ISSUE TITLE
Test server doesn't work

### ISSUE THREAD

**Issue by Creeperface01** [NiclasOlofsson/MiNET#49]

**Comment by kennyvv** [comment]
This happens if a build has failed. I'll look into fixing this.

**Comment by kennyvv** [comment]
Fixed

**Comment by Creeperface01** [comment]
![screenshot_2015-07-10-07-09-44](https://cloud.githubusercontent.com/assets/10363500/8612562/aaa3145e-26d2-11e5-9c25-213929dd6425.png)
I mean this test server.

**Comment by kennyvv** [comment]
Service stuck restarting, searching for issue...

**Comment by kennyvv** [comment]
Fixed for sure now ;)
Problem was outdated plugin. OOOPS

**Comment by Creeperface01** [comment]
Oooooooo WOW!!!!  It is the most stable MCPE server!  and woter is not laggy like in pocketmine!! 
I hope your server will be like Bukkit in PC :)

![screenshot_2015-07-12-18-01-45](https://cloud.githubusercontent.com/assets/10363500/8638588/75c57d18-28c0-11e5-87b1-effce39a0f22.png)

**Comment by NiclasOlofsson** [comment]
Credit for world generator goes to @kennyvv
