### ISSUE TITLE
make it possible to translate strings in MiNET to other languages

### ISSUE THREAD

**Issue by zzm317** [NiclasOlofsson/MiNET#5]
make it possible to translate strings in MiNET to other languages!
Give me candy after you done it LOL

**Comment by kennyvv** [comment]
This is a nice feature indeed, like i said before. I'm planning on adding support for this. However this does not have any high priority.

**Comment by NiclasOlofsson** [comment]
Well, luckily for them I asked them to add this issue, since it is a priority to me. I already said I'll fix it when I'm done with smelting.
