### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by Tee7even** [NiclasOlofsson/MiNET#51]
I know that the Plugin API is still in early (or not) development and maybe this is already planned, but after looking at some example plugins, I think that this is something different from what I've seen in PocketMine or Bukkit.
A Bukkit-like APIs would give plugin developers the better plugin portability from both Bukkit and PocketMine, since both have similar APIs. And I don't see any reasons why this couldn't be done, except maybe if this couldn't be done in C# at all or this server works completely different...
Anyways, Mi-NET seems to be the most alive alternative to PocketMine. Keep up the good work. :)

**Comment by Creeperface01** [comment]
RedstoneLamp has similar API too

**Comment by RandomAltThing** [comment]
The goal of MiNET is not to be the same as PocketMine or Bukkit. Many people will be familiar with PocketMine or Bukkit API's, but they with just have to learn ours. Sorry :)

**Comment by Tee7even** [comment]
Well, that's a big barrier for much people to switch to MiNET... Okay. :\
P.S. Also somebody should think a bit about the name of this project, it looks like [a transliterated obscene word in Russian](https://translate.google.com/#ru/en/%D0%BC%D0%B8%D0%BD%D0%B5%D1%82).

**Comment by RandomAltThing** [comment]
@Tee7even Further on in MiNET development, I will create a organisation with MiNET plugins. It looks like http://github.com/MiNET-Plugins is abandoned

**Comment by NiclasOlofsson** [comment]
A bukkit-type API can be achieved, and has been achieved in closed source on several occations and various degrees of conformity to the originals. The role of MiNET in this is to hide as much of the network as possible while not restricting developers to a specific type of functionality that the server enforce. This is not PocketMine and the goal is not to be easy to use for anyone without professional programming skills. The target-group is also very different and users would be large-scale MCPE hosting sites with 10 or more servers running.

I'm fully aware of what the name means in Russian :-)
