### ISSUE TITLE
problem connect player verzion 1.16.100

### ISSUE THREAD

**Issue by BatUnt** [NiclasOlofsson/MiNET#535]
__   __  ___   __    _  _______  _______
|  |_|  ||   | |  |  | ||       ||       |
|       ||   | |   |_| ||    ___||_     _|
|       ||   | |       ||   |___   |   |
|       ||   | |  _    ||    ___|  |   |
| ||_|| ||   | | | |   ||   |___   |   |
|_|   |_||___| |_|  |__||_______|  |___|

Are you blessed with HW accelerated vectors? Yep!
Operations timed using the system's high-resolution performance counter.
  Timer frequency in ticks per second = 1000000000
  Timer is accurate within 1 nanoseconds
 WARN [AnvilWorldProvider] - No level.dat found at home/game/minet/worlds/level.                                                                                                                                                             dat. Creating empty.
MiNET running. Press <enter> to stop service.
 WARN [Level] - Unloaded 12 chunks, 1245 chunks remain cached
 WARN [LoginMessageHandler] - Encrypted connection established with BatUnt using                                                                                                                                                              MC version 1.16.100 with protocol version 419
 WARN [Player] - Cache status: Enabled
ERROR [Player] - A level 2 packet violation of type 0 for packet 0x7
 WARN [Datagram] - CreateDatagrams single message
 WARN [Player] - Disconnected crashed player BatUnt/87.244.204.144 from level <U                                                                                                                                                             nknown>, reason: Client requested disconnected

**Comment by TobiasG-DE** [comment]
If I'm not mistaken that version is not supported _yet_, you need to wait for a contributor to update it

**Comment by BatUnt** [comment]
well thank you
