### ISSUE TITLE
Example plugins don't work

### ISSUE THREAD

**Issue by ElectroGamesYT** [NiclasOlofsson/MiNET#593]
None of the example plugins work. And yes, I have set the plugins directory and enabled the plugins via server.conf.
Also, what worlds does MiNET support? I've tried Bedrock Edition, PocketMine, and Java Edition 1.17 and 1.8.9 worlds.

**Comment by kennyvv** [comment]
The example plugins work fine, probably misconfiguration.

**Comment by ElectroGamesYT** [comment]
Confutation is fine.
