### ISSUE TITLE
Feature list.

### ISSUE THREAD

**Issue by tonibm19** [NiclasOlofsson/MiNET#6]
First of all, Thanks for trying to do this.

As the issue says, it would be fine if there was a feature list.

Also, a question, how much ram does this server take, aproximately?

**Comment by FDKPIBC** [comment]
what is your means Feature list?

**Comment by NiclasOlofsson** [comment]
I would guess a list of implemented features, or roadmap. The current feature list is in the wiki.

How much RAM .. well, below 200mb eh.
