### ISSUE TITLE
ВНИМАНИЕ АНЕКДОТ 

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [NiclasOlofsson/MiNET#635]
![Screenshot_2023_0213_165159](https://user-images.githubusercontent.com/68144848/223039730-64383a23-e51d-490a-a8b9-dca4c0ce784f.jpg)

**Comment by kennyvv** [comment]
Closing as i have no idea what this is.

**Comment by SPAWNRYS-ban** [comment]
> 

This is an anecdote, so no closure

**Comment by dktapps** [comment]
If the Google Lens translation is at all accurate, this is wildly inappropriate and hardly qualifies as a joke

**Comment by Miralim0** [comment]
Ахахахахха, ну я тоже думаю как блин так говорить минет или майнет
