### ISSUE TITLE
Project's name issue

### ISSUE THREAD

**Issue by Charelene** [NiclasOlofsson/MiNET#64]
It's pretty good to see the best alternative to the PocketMine yet, but the name seems to be really awkward in Russian, and I've got some proofs to you, to be fully assured.
![Translation](https://pp.vk.me/c622527/v622527959/3e87e/eFjdXV22UXY.jpg)
I'm actually sincerely worried about this issue, because the could be misunderstanded in Russian (like blowing frome the others, like PocketMine, or treatment to the users of this project, which is actually not true). So I'm really looking forward to solving this major issue as soon as possible.

**Comment by NiclasOlofsson** [comment]
The car brand Kia means chain-smoker in Thai. Not really that good for a car if you think about it.

Changing the name would be really complex and if that happen, it would have to be in the future on low priority. So just to not have any confusments regarding that, i consider PocketMine partners in crime, and would still recommend using that over MiNET for 99% of the users any day.
