### ISSUE TITLE
Item entities dropped by player behave incorrect

### ISSUE THREAD

**Issue by NiclasOlofsson** [NiclasOlofsson/MiNET#65]
Item drops should use the head yay and pitch of the player to throw the item, currently it does not. Then normal gravity should take over. In order to do this, entity movements with gravity should be implemented similar to projectiles and mobs, but on higher level (Entity).

**Comment by jose-vm** [comment]
Another bug related to them: all ItemEntities float in the air if their support block is removed and/or if you spawn them through code in the air.

**Comment by NiclasOlofsson** [comment]
It's deliberate until the physics is correct. Enable AI if you want them to be emulated by the client ,but not they won't be in the correct place on the server, and pickup won't work.
