### ISSUE TITLE
Minet won't start or compile under linux.

### ISSUE THREAD

**Issue by tonibm19** [NiclasOlofsson/MiNET#7]
When starting:
mono MiNET.Service.exe
 INFO [NetService] - Starting MiNET
 INFO [iNetServer] - Loading settings...
 INFO [iNetServer] - Loading plugins...
 INFO [iNetServer] - Plugins loaded!
 INFO [iNetServer] - Server open for business...
MiNET runing. Press <enter> to stop service..

Unhandled Exception:
System.NotImplementedException: The requested feature is not implemented.
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, CompressionLevel compressionLevel, Boolean leaveOpen) [0x00000] in <filename unknown>:0
  at MiNET.Utils.ZLibStream..ctor (System.IO.Stream stream, CompressionLevel level, Boolean leaveOpen) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) MiNET.Utils.ZLibStream:.ctor (System.IO.Stream,System.IO.Compression.CompressionLevel,bool)
  at MiNET.Worlds.ChunkColumn.GetBytes () [0x00000] in <filename unknown>:0
  at MiNET.Worlds.Level.<Initialize>b__0 (System.Object state) [0x00000] in <filename unknown>:0

When compiling
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Anvil/Craft.Net.Anvil.csproj'
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Common/Craft.Net.Common.csproj'
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/externals/fNbt/fNbt/fNbt.csproj'
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.TerrainGeneration/Craft.Net.TerrainGeneration.csproj'
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Logic/Craft.Net.Logic.csproj'
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Physics/Craft.Net.Physics.csproj'
                Project "/minet/MiNET-PC-interoperability/src/MiNET/MiNET/MiNET.csproj" (default target(s)):
                        Target RestorePackages:
                                Executing: mono --runtime=v4.0.30319 "/minet/MiNET-PC-interoperability/src/MiNET/.nuget/NuGet.exe" install "/minet/MiNET-PC-interoperability/src/MiNET/MiNET/packages.config" -source ""   -RequireConsent -solutionDir "/minet/MiNET-PC-interoperability/src/MiNET/"
                                Restoring NuGet packages...
                                To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
                                WARNING: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
                                Unable to find version '1.0.7' of package 'Deedle'.
/minet/MiNET-PC-interoperability/src/MiNET/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 "/minet/MiNET-PC-interoperability/src/MiNET/.nuget/NuGet.exe" install "/minet/MiNET-PC-interoperability/src/MiNET/MiNET/packages.config" -source ""   -RequireConsent -solutionDir "/minet/MiNET-PC-interoperability/src/MiNET/"' exited with code: 1.
                        Task "Exec" execution -- FAILED
                        Done building target "RestorePackages" in project "/minet/MiNET-PC-interoperability/src/MiNET/MiNET/MiNET.csproj".-- FAILED
                Done building project "/minet/MiNET-PC-interoperability/src/MiNET/MiNET/MiNET.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln".-- FAILED
Done building project "/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln".-- FAILED

Build FAILED.

Warnings:

/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln:  warning : Project file /minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Anvil/Craft.Net.Anvil.csproj referenced in the solution file, not found. Ignoring.
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln:  warning : Project file /minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Common/Craft.Net.Common.csproj referenced in the solution file, not found. Ignoring.
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln:  warning : Project file /minet/MiNET-PC-interoperability/external/craft.net/externals/fNbt/fNbt/fNbt.csproj referenced in the solution file, not found. Ignoring.
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln:  warning : Project file /minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.TerrainGeneration/Craft.Net.TerrainGeneration.csproj referenced in the solution file, not found. Ignoring.
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln:  warning : Project file /minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Logic/Craft.Net.Logic.csproj referenced in the solution file, not found. Ignoring.
/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln:  warning : Project file /minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Physics/Craft.Net.Physics.csproj referenced in the solution file, not found. Ignoring.

Errors:

/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln (default targets) ->
(Build target) ->

        /minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Anvil/Craft.Net.Anvil.csproj'
        /minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Common/Craft.Net.Common.csproj'
        /minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/externals/fNbt/fNbt/fNbt.csproj'
        /minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.TerrainGeneration/Craft.Net.TerrainGeneration.csproj'
        /minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Logic/Craft.Net.Logic.csproj'
        /minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln: error : Could not find the project file '/minet/MiNET-PC-interoperability/external/craft.net/source/Craft.Net.Physics/Craft.Net.Physics.csproj'

/minet/MiNET-PC-interoperability/src/MiNET/MiNET.sln (default targets) ->
(Build target) ->
/minet/MiNET-PC-interoperability/src/MiNET/MiNET/MiNET.csproj (default targets) ->
/minet/MiNET-PC-interoperability/src/MiNET/.nuget/NuGet.targets (RestorePackages target) ->

        /minet/MiNET-PC-interoperability/src/MiNET/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 "/minet/MiNET-PC-interoperability/src/MiNET/.nuget/NuGet.exe" install "/minet/MiNET-PC-interoperability/src/MiNET/MiNET/packages.config" -source ""   -RequireConsent -solutionDir "/minet/MiNET-PC-interoperability/src/MiNET/"' exited with code: 1.

         6 Warning(s)
         7 Error(s)

Time Elapsed 00:00:10.5096950

**Comment by kennyvv** [comment]
Hello, 
I looked at your Compile log. Did you use GIT when download MiNET?
If not, please use git. Also, for the 
<code>
System.NotImplementedException: The requested feature is not implemented.
at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, CompressionLevel compressionLevel, Boolean leaveOpen) [0x00000] in :0
at MiNET.Utils.ZLibStream..ctor (System.IO.Stream stream, CompressionLevel level, Boolean leaveOpen) [0x00000] in :0
at (wrapper remoting-invoke-with-check) MiNET.Utils.ZLibStream:.ctor (System.IO.Stream,System.IO.Compression.CompressionLevel,bool)
at MiNET.Worlds.ChunkColumn.GetBytes () [0x00000] in :0
at MiNET.Worlds.Level.b__0 (System.Object state) [0x00000] in :0
</code>
Error i will look into this on Linux / Mac, and try and fix it!

**Comment by kennyvv** [comment]
I also just noticed you use the 'MiNET-PC-interoperability' branch.
Please note that this is a work in progress branch, and not yet ready for regular use!

**Comment by NiclasOlofsson** [comment]
Please check your version of mono. It appear as if this was fixed somewhere around version 2.8.

**Comment by tonibm19** [comment]
I tried with the 2 branches, none worked, I'll try with your advices,

**Comment by tonibm19** [comment]
Same error cloning the 2 branches with Git

**Comment by kennyvv** [comment]
Hi, please try to clone using the following Command: "git clone --recursive https://github.com/NiclasOlofsson/MiNET.git", this command also downloads submodules. These are needed for some functions in MiNET. If you already cloned the repo you can use the following command " git submodule update --init --recursive ". If this doesn't work, please tell us :+1:

**Comment by tonibm19** [comment]
It doesn't work, but now I only get 1 error:

                Done building project "/minet/MiNET/external/craft.net/source/Craft.Net.Anvil/Craft.Net.Anvil.csproj".
                Project "/minet/MiNET/external/craft.net/source/Craft.Net.TerrainGeneration/Craft.Net.TerrainGeneration.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Debug Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target GenerateTargetFrameworkMonikerAttribute:
                        Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                        Target CoreCompile:
                        Skipping target "CoreCompile" because its outputs are up-to-date.
                Done building project "/minet/MiNET/external/craft.net/source/Craft.Net.TerrainGeneration/Craft.Net.TerrainGeneration.csproj".
                Project "/minet/MiNET/external/craft.net/source/Craft.Net.Physics/Craft.Net.Physics.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Debug Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target GenerateTargetFrameworkMonikerAttribute:
                        Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                        Target CoreCompile:
                        Skipping target "CoreCompile" because its outputs are up-to-date.
                Done building project "/minet/MiNET/external/craft.net/source/Craft.Net.Physics/Craft.Net.Physics.csproj".
                Project "/minet/MiNET/src/MiNET/MiNET/MiNET.csproj" (default target(s)):
                        Target RestorePackages:
                                Executing: mono --runtime=v4.0.30319 "/minet/MiNET/src/MiNET/.nuget/NuGet.exe" install "/minet/MiNET/src/MiNET/MiNET/packages.config" -source ""   -RequireConsent -solutionDir "/minet/MiNET/src/MiNET/"
                                Restoring NuGet packages...
                                To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
                                WARNING: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
                                Unable to find version '1.0.7' of package 'Deedle'.
/minet/MiNET/src/MiNET/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 "/minet/MiNET/src/MiNET/.nuget/NuGet.exe" install "/minet/MiNET/src/MiNET/MiNET/packages.config" -source ""   -RequireConsent -solutionDir "/minet/MiNET/src/MiNET/"' exited with code: 1.
                        Task "Exec" execution -- FAILED
                        Done building target "RestorePackages" in project "/minet/MiNET/src/MiNET/MiNET/MiNET.csproj".-- FAILED
                Done building project "/minet/MiNET/src/MiNET/MiNET/MiNET.csproj".-- FAILED
                Project "/minet/MiNET/external/craft.net/source/Craft.Net.Logic/Craft.Net.Logic.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Debug Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target GenerateTargetFrameworkMonikerAttribute:
                        Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
                        Target CoreCompile:
                        Skipping target "CoreCompile" because its outputs are up-to-date.
                Done building project "/minet/MiNET/external/craft.net/source/Craft.Net.Logic/Craft.Net.Logic.csproj".
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/minet/MiNET/src/MiNET/MiNET.sln".-- FAILED
Done building project "/minet/MiNET/src/MiNET/MiNET.sln".-- FAILED

Build FAILED.
Errors:

/minet/MiNET/src/MiNET/MiNET.sln (default targets) ->
(Build target) ->
/minet/MiNET/src/MiNET/MiNET/MiNET.csproj (default targets) ->
/minet/MiNET/src/MiNET/.nuget/NuGet.targets (RestorePackages target) ->

        /minet/MiNET/src/MiNET/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 "/minet/MiNET/src/MiNET/.nuget/NuGet.exe" install "/minet/MiNET/src/MiNET/MiNET/packages.config" -source ""   -RequireConsent -solutionDir "/minet/MiNET/src/MiNET/"' exited with code: 1.

         0 Warning(s)
         1 Error(s)

Time Elapsed 00:00:15.2864530

**Comment by kennyvv** [comment]
Hmm, the only problem i can see is that it can't seem to find Deedle 1.0.7...
However, when i check the NuGet Gallery it is still on there. Ill let you know as soon as i found a solution. If you got any question, please ask them ;)

**Comment by kennyvv** [comment]
Strange, i just tried it out on OSX. And it seems to work fine there. I'll also setup a Linux VM soon. What Linux Distrobution are you using?

**Comment by tonibm19** [comment]
Debian 7

**Comment by NiclasOlofsson** [comment]
http://stackoverflow.com/questions/15181888/nuget-on-linux-error-getting-response-stream

**Comment by NiclasOlofsson** [comment]
Please update mono if you are on Debian.

http://unix.stackexchange.com/questions/151751/why-is-mono-complete-completely-outdated-on-all-versions-of-debian

The fix according to mono actually seems to be in 3.10.x builds. And debian only distribute 3.8.x even on unstable debian.

**Comment by tonibm19** [comment]
thanks, it works!

**Comment by NiclasOlofsson** [comment]
Thanks for the verfication. Closed it a "bit" pre-maturely. Should have asked you first :-P
