### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Jelly9912** [NiclasOlofsson/MiNET#75]
fatal: Could not read from remote repository

Why?

**Comment by kennyvv** [comment]
Hi Jelly, 
I suppose you get this error with GIT?

**Comment by DevBrad** [comment]
I have the same issue, and yes, with Git using the command provided in the README.md

**Comment by PEMapModder** [comment]
Then use `git clone --recursive https://github.com/NiclasOlofsson/MiNET.git`, I would.

**Comment by DevBrad** [comment]
Okay thanks, it worked. But now when I run "cd src/MiNET/MiNET.Service/bin/Debug; mono MiNET.Service.exe" it echoes " 'MiNET.Service.exe': No such file or directory"

**Comment by DevBrad** [comment]
Any idea why?

**Comment by CavinMiana** [comment]
Look at the tutorial. Change the directory to wherever you want MiNET files to go.
