### ISSUE TITLE
How do I run on WIndows10?

### ISSUE THREAD

**Issue by ItzBulkDev** [NiclasOlofsson/MiNET#76]
Need to know how to run MiNet on Windows 10

**Comment by MajikalPayton** [comment]
Like most C#/.NET applications, it can be ran in [Mono.](http://www.mono-project.com/)
:)

**Comment by ItzBulkDev** [comment]
@MajikalPayton What is the command I would run in Mono?

**Comment by MajikalPayton** [comment]
As stated in the README, do the following;
1. Make sure you have Mono installed.
2. cd to the current directory in which MiNET is located.
3. Run ```xbuild src/MiNET/MiNET.sln```.
4. There should now be an executable that can only be ran (as far as I know) as a command line application. To run it, run ```cd src/MiNET/MiNET.Service/bin/Debug; mono MiNET.Service.exe```
5. Profit???

**Comment by MajikalPayton** [comment]
If this works for you, please close this issue. :)

**Comment by FDKPIBC** [comment]
If you are a windows system, no need to install mono,just download zip file in https://ci.appveyor.com/project/NiclasOlofsson/MiNET/branch/master/artifacts,and unzip the downloaded file,run MiNETService.exe.

**Comment by MajikalPayton** [comment]
I couldn't find that link. :p Thanks! :) The creator of this issue should close it as soon as their problem has been solved.

**Comment by MajikalPayton** [comment]
https://ci.appveyor.com/project/NiclasOlofsson/MiNET/branch/master/artifacts

**Comment by kennyvv** [comment]
Question like this should not be asked in here.
This is made for ISSUES. Not for questions. If you do in fact have questions feel free to join the GitterChat.
