### ISSUE TITLE
Nether Reactor Core isn't implemented as a block

### ISSUE THREAD

**Issue by jose-vm** [NiclasOlofsson/MiNET#85]

**Comment by Tarik02** [comment]
What??? Neither Reactor Core can be removed!

**Comment by jose-vm** [comment]
I mean as an actual file block

**Comment by Tarik02** [comment]
Because it must removed from minecraft.

**Comment by Pub4Game** [comment]
@Tarik02 It will not be removed from Minecraft! He will remain as a decorative block in creative

**Comment by SkygridRex** [comment]
@Pub4Game yes, the nether reactor has been removed from the inventory but you can get this block editing your inventory

**Comment by NiclasOlofsson** [comment]
Nothing to do here. Works just fine if you use new Block(...)
